### ISSUE TITLE
te_loader.py EFI_TE_IMAGE_HEADER invalid size

### ISSUE THREAD

**Issue by valeri2** [snare/ida-efiutils#3]
te_loader.py loader has a bug in line 124.

```
f.seek(sec.ptr_to_data - te.stripped_size + 24)
```

Size of EFI_TE_IMAGE_HEADER is invalid (ignored a member DataDirectory). 
Thus, the size of the sections is not calculated correctly.

Fix: 

```
f.seek(sec.ptr_to_data - te.stripped_size + 24 + 8 * 2)
```

**Comment by snare** [comment]
OK, thanks!
