### ISSUE TITLE
Error import behemoth.h

### ISSUE THREAD

**Issue by GH0st3rs** [snare/ida-efiutils#4]
Hi. I have some trouble with import .h file in IDA 6.8 x64. I use VS10, and set Compiler options, but IDA print me next errors:

```
behemoth.h,66: Syntax error near: @type VA_LIST
behemoth.h,21767: Undefined type name 'VOID'
behemoth.h,21891: Syntax error near: FILLER
behemoth.h,21892: Syntax error near: }
behemoth.h,21923: Syntax error near: PEI_CORE_FV_HANDLE
behemoth.h,21959: Syntax error near: }
```

**Comment by perks** [comment]
Gonna have to wisdom of the ancients you on your error:

![image](https://cloud.githubusercontent.com/assets/1820298/23279185/47a73710-f9e2-11e6-98b6-65df827d58ec.png)

**Comment by feisuzhu** [comment]
+1
![image](https://user-images.githubusercontent.com/857880/29750170-abddd28a-8b6d-11e7-9951-8b463bc63ce3.png)

**Comment by feisuzhu** [comment]
Meh, solved.

@perks 

Manually add 
```
typedef unsigned char FILLER;
typedef void VOID;
```

Choose gcc on Options -> Compiler
